# Generated by Django 5.0.2 on 2025-07-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Development'), ('design', 'UI/UX Design'), ('seo', 'SEO Optimization'), ('consultation', 'Consultation'), ('other', 'Other')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_type', models.CharField(choices=[('hourly', 'Per Hour'), ('fixed', 'Fixed Price'), ('monthly', 'Per Month')], max_length=20)),
                ('icon', models.CharField(default='fas fa-cog', max_length=50)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('team_size', models.CharField(blank=True, max_length=50)),
                ('delivery_time', models.CharField(blank=True, max_length=50)),
                ('additional_info', models.TextField(blank=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('features', models.ManyToManyField(blank=True, to='services.servicefeature')),
            ],
            options={
                'ordering': ['order', '-is_popular', '-created_at'],
            },
        ),
    ]
