# Generated by Django 5.0.2 on 2025-07-19 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_bio_profile_birth_date_profile_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='about_content',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='social_facebook',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='social_github',
            new_name='instagram_url',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='social_linkedin',
            new_name='linkedin_url',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='social_twitter',
            new_name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_logo',
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('verification_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('admin_verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_approved', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
